# Use Python 3.12 as the base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the Python source code to the container
COPY student_app.py /app

# Run the Python application
CMD ["python", "student_app.py"]
